baseurl = "/"
languageCode = "en-us"
title = "Andrew H. Thomas"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = "UA-12433439-2"
# Define how many posts should appear on a site
paginate = 10
PygmentsCodeFences = true
pygmentsuseclasses = true
[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Andrew H. Thomas"
	description = "A Drupal and PHP Web developer working in Philadelphia, and currently employed by Scribe Inc.  I enjoy coding in Linux using Sublime Text."

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []

	[params.about]
		hide  = false
		title = "Let’s create something that your users will love."
		content = "We're a software design and development agency that builds custom web and mobile products for our clients."

	[params.contact]
		hide  = false
		title = "Get In Touch"
		content = "Accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna. Accumsan orci faucibus id eu lorem semper nunc nisi lorem vulputate lorem neque lorem ipsum dolor."

		address = [
			"5123 Locust Street",
			"Philadelphia, PA 19139",
			"United States"
		]
		phone = "000-000-0000"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "hello@example.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			nameFirst = "First name"
      nameLast = "Last name"
      organization = "Organization"
      title = "Title"
      phone = "Phone"
			email = "Email"
      how = "How did you hear about us?"
      tell = "Tell us about your project"
      budget = "What's your budget for this work?"
      timeline = "What's your timeline?"
			message = "Message"
      success = "What would make your project a success?"
      contact = "May we stay in touch?"
			submit = "Send"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 1

[[menu.main]]
	name = "About"
	url  = "about"
	weight = 5

[[menu.main]]
	name = "Contact"
	url  = "contact"
	weight = 10
